# fly.toml app configuration file generated for festivalpos-backend on 2024-06-01T14:28:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'festivalpos-backend'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'npm run typeorm:migrate'

[env]
  ADMIN_APP_HOST = ''
  ADMIN_APP_PORT = '5173'
  EXTERNAL_HOST = 'festivalpos.aufgetischt.sg'
  EXTERNAL_PORT = '443'
  EXTERNAL_SCHEME = 'https'
  HOST = 'localhost'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
